  name: AutoVersions CI
  on:
    push:
      branches:
        - main
  jobs:
    build:
      name: Build Node
      runs-on: ubuntu-latest
      steps:
        - name: chekout brabch
          uses: actions/checkout@v2
        - name: node version
          uses: actions/node-version@v2
          with:
            node-version: "14"
          run: |
            npm install
            npm run test
